# Generated by Django 3.1.13 on 2021-08-18 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20210815_1224'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
