# Generated by Django 3.1.13 on 2021-08-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210820_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
